### ISSUE TITLE
useradd fails in some cases

### ISSUE THREAD

**Issue by udeved** [artix-linux/opensysusers#1] opened 2017-07-31 09:28 UTC
Hi Chris,

I tried to track down some issue with sysusers.
I added an updated hook, and this is output with some echo vars.

```
:: Starte post-transaction hooks...
(1/1) Updating system user accounts...
u
dbus
81

/
g
locate
21

/
u
mysql
89

/var/lib/mysql
u
ldap
439

Server" /var/lib/openldap
useradd: Ungültiges Home-Verzeichnis »Server" /var/lib/openldap«
g
rfkill
-

/
u
uuidd
68

/
g
vboxusers
108

/
```

The thing fails with openldap, the description in the ldap.conf, the gecko var that is I think gets a split string passed. Something with the parser is not right if the gecko has white spaces, ie if its not empty or not just a single word.

ldap.conf...

`u ldap 439 "LDAP Server" /var/lib/openldap`

**Comment by cromerc** [comment] 2017-07-31 20:11
I see what the issue is, I will take a look at it.

**Comment by udeved** [comment] 2017-08-01 15:49
I think 0.2.1 still has issues.
If I install openldap, a ldap user should be created.

(1/1) Creating temporary files...
chown: ungültiger Benutzer: „ldap“

but tmpfiles fails.

**Comment by cromerc** [comment] 2017-08-01 15:51
tmpfiles is another software, I didn't write it, that is from upstream at OpenRC

I will double check with ldap, I tried with a some other conf files that had spaces in their gecos and it worked, just not openldap specificlaly

**Comment by cromerc** [comment] 2017-08-01 16:14
Should now be fixed via 15ff42b18ab0c3cff84bbc5b65b431c1971ffa9c

**Closed as completed by cromerc** 2017-08-01 16:14 UTC
